project:
  type: website
  output-dir: docs

website:
  title: "Aidan Marnane"
  image: files/profile.jpg
  navbar:
    right:
      - about.qmd
      - posts.qmd
      - icon: github
        href: https://github.com/amarnane
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/a_marnane
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



