project:
  type: website
  output-dir: docs

freeze: true

website:
  title: "Aidan Marnane"
  favicon: files/icon.png
  image: files/profile.jpg
  navbar:
    right:
      - about.qmd
      - posts.qmd
      - text: Thesis
        href: thesis.qmd
      - text: SimnetPy
        url:  https://amarnane.github.io/simnetpy
      - icon: github
        href: https://github.com/amarnane
        aria-label: GitHub
      # - icon: twitter
      #   href: https://twitter.com/a_marnane
      - icon: linkedin
        text: LinkedIn
        href: https://uk.linkedin.com/in/aidan-marnane-124391138
format:
  html:
    # theme: [ath, styles/mytheme.scss]
    theme:
      light: [flatly, styles/mytheme.scss]
      dark: [darkly, styles/darktheme.scss]
    css: styles.css
    highlight-style: atom-one



